server:
  port: 12301
  servlet:
    context-path: /logger

spring:
  # 数据库链接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/logger?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

yeecode:
  objectLogger:
    serverAddress: http://127.0.0.1:12301
    businessAppName: ObjectLoggerServer
    autoLogAttributes: true

mybatis:
  check-config-location: true
  #  mybatis框架配置文件，对mybatis的生命周期起作用
#  config-location: "classpath:mybatis-config.xml"
  #  配置xml路径
  mapper-locations: "classpath:mapper/*Mapper.xml"
  #  配置model包路径
  type-aliases-package: "com.github.yeecode.objectlogger.client.model"
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl